import api from './api'

const adminService = {
  getDashboard: () => api.get('/admin/dashboard'),
  getUsers: (params) => api.get('/admin/users/all', { params }),
  createUser: (data) => api.post('/admin/users', data),
  deleteUser: (id) => api.delete(`/admin/users/${id}`),
  getSystemSettings: () => api.get('/admin/settings'),
  getPublicWasteTypes: () => api.get('/api/settings/waste-types', { skipAuthRedirect: true }),
  updateSystemSettings: (data) => api.put('/admin/settings', data),
  createOrder: (data) => api.post('/admin/orders', data),
  updateDriverStatus: (id, status) => api.put(`/admin/drivers/${id}/status`, { status }),
  getProfile: () => api.get('/user/profile', { skipAuthRedirect: true }),
  updateProfile: (data) => api.put('/user/profile', data),
  updateDriver: (id, data) => api.put(`/user/profile/${id}`, data),
  toggleUserBan: (id) => api.put(`/admin/toggle-ban/${id}`),
  getOrders: (params) => api.get('/api/wasterequest', { params }),
  updateOrder: (id, data) => api.put(`/api/wasterequest/${id}`, data),
  deleteOrder: (id) => api.delete(`/api/wasterequest/${id}`),
  getBins: (params) => api.get('/api/bins', { params }),
  getBinStats: () => api.get('/api/bins/stats'),
  getBinsForMap: () => api.get('/api/bins/map'),
  createBin: (data) => api.post('/api/bins', data),
  updateBin: (id, data) => api.put(`/api/bins/${id}`, data),
  deleteBin: (id) => api.delete(`/api/bins/${id}`),
  getRoutes: (params) => api.get('/api/route', { params }),
  getRoute: (id) => api.get(`/api/route/${id}`),
  createRoute: (data) => api.post('/api/route', data),
  updateRoute: (id, data) => api.patch(`/api/route/${id}`, data),
  deleteRoute: (id) => api.delete(`/api/route/${id}`),
  getReports: (params) => api.get('/api/stats/admin-stats', { params }),
  getRewards: (params) => api.get('/api/rewards', { params }),
  createReward: (data) => api.post('/api/rewards', data),
  updateReward: (id, data) => api.put(`/api/rewards/${id}`, data),
  deleteReward: (id) => api.delete(`/api/rewards/${id}`),
  getRewardClaims: () => api.get('/api/rewardclaim'),
  getSupport: (params) => api.get('/api/message', { params }),
  markSupportRead: (id) => api.patch(`/api/message/${id}/read`),
  replyToSupport: (id, reply) => api.post(`/api/message/${id}/reply`, { reply }),
}

export default adminService
